<a href="https://colab.research.google.com/github/rubalex7328/PostgressDB/blob/master/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.arange(1,11)
print(a)


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
m = np.zeros((3,3),dtype=float)
print(m)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
m55 = np.random.random((5,5))*9 + 1
print(m55)


[[1.12249734 5.53736279 6.64110614 7.31783118 6.10836734]
 [9.7616009  3.75430772 6.62822114 2.66326747 1.40681008]
 [3.4815551  4.50866235 9.30518181 7.61413532 8.3501174 ]
 [5.55311492 9.64451598 3.99198287 4.32756148 1.22784361]
 [2.94649106 1.23584287 4.51810941 2.66588944 8.30689068]]


In [ ]:
m44 = np.random.random((4,4))
print(m44)


[[0.3587929  0.51634451 0.68391356 0.95187414]
 [0.72259133 0.24958208 0.72825386 0.09979788]
 [0.03970722 0.95011863 0.4523365  0.45083408]
 [0.74721273 0.44989407 0.45830004 0.0665488 ]]


In [ ]:
a1 = np.random.random(5)*9+1
a2 = np.random.random(5)*9+1
print(a1)
print(a2)
print(a1+a2)
print(a1-a2)
print(a1*a2)


[2.07222958 1.7597937  8.26688188 1.61681869 1.69839046]
[8.20204463 8.82860728 4.02367749 9.44701411 3.03052923]
[10.27427421 10.58840098 12.29055936 11.0638328   4.72891969]
[-6.12981504 -7.06881357  4.24320439 -7.83019541 -1.33213878]
[16.99651952 15.53652748 33.2632665  15.27410902  5.14702193]


In [ ]:
b1 = np.random.random(7)
b2 = np.random.random(7)
print('Ск.добуток',np.dot(b1,b2))


Ск.добуток 1.733913957251686


In [ ]:
m1 = np.random.random((2,2))*9+1
m2 = np.random.random((2,3))*9+1
print(m1 @ m2)


[[62.83917529 61.24885925 45.69680464]
 [85.70553354 92.78079761 69.01392211]]


In [ ]:
m33 = np.random.random((3,3))*9 + 1
print(np.linalg.inv(m33))


[[-0.07161284 -0.19933415  0.20881123]
 [ 0.16009277  0.00281119 -0.04026133]
 [-0.00817893  0.18605086 -0.06717889]]


In [ ]:
m44 = np.random.random((4,4))
print(m44.T)


[[0.54455384 0.51734928 0.47333881 0.73690828]
 [0.56321295 0.75199316 0.75710031 0.97253733]
 [0.54037177 0.58256076 0.02217265 0.9887553 ]
 [0.55314987 0.09631302 0.25136589 0.8188867 ]]


In [ ]:
m34 = np.random.random((3,4))*9 + 1
v4 = np.random.random(4)*9 + 1
print(np.dot(m34,v4))


[127.62554381 175.80194023 102.46096822]


In [ ]:
m23 = np.random.random((2,3))
v3 = np.random.random(3)
print(np.dot(m23,v3))


[0.77362505 0.64803195]


In [ ]:
m22_1 = np.random.random((2,2))*9 + 1
m22_2 = np.random.random((2,2))*9 + 1
print(m22_1*m22_2)


[[26.42967051 23.79887095]
 [38.45314026 90.12762357]]


In [ ]:
m55 = np.random.random((5,5))*99 + 1
print(m55.sum())


1295.1388503386493


In [ ]:
m44_1 = np.random.random((4,4))*9 + 1
m44_2 = np.random.random((4,4))*9 + 1
print(m44_1-m44_2)


[[ 0.34681897 -4.54657192  0.31586966  2.94000168]
 [-1.35053058  0.18491515 -0.72636496 -0.53305439]
 [ 2.93884267 -4.06547792 -2.09817196 -4.62351414]
 [ 8.10844969 -4.99333569 -3.25270115  3.97172889]]


In [ ]:
m33 = np.random.random((3,3))
print(m33)
sum_rows = m33.sum(axis=1)
print(sum_rows[:np.newaxis])


[[0.01525497 0.59884338 0.60380454]
 [0.10514769 0.38194344 0.03647606]
 [0.89041156 0.98092086 0.05994199]]
[1.21790289 0.52356719 1.93127441]


In [ ]:
m34 = np.array([np.arange(1,5,1),np.arange(5,9,1),np.arange(9,13,1)])
print(m34)
print(m34*m34)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [ ]:
v4 = np.random.randint(1,50, 4)
print(v4)
print(np.sqrt(v4))


[46 36 38 13]
[6.78232998 6.         6.164414   3.60555128]


In [ ]:
import numpy.ma as ma
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a = ma.MaskedArray(arr)
m = ma.masked_where(a % 2 != 0, a)
print(m.filled(-1))



[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a.reshape((2,5)))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
a = np.array([[0, 1],[2, 3]])
b = np.array([[4, 5],[6, 7]])
print(a.sum(axis=0))
print(b.sum(axis=0))
print(a.sum(axis=0)+b.sum(axis=0))


[2 4]
[10 12]
[12 16]


In [ ]:
a = np.array([1,2,3])
# [1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
b = np.vstack((a,a,a))
print(np.concatenate((np.concatenate((b[0:,0],b[0:,1],b[0:,2])),np.concatenate((a,a,a),axis=0))))


[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [ ]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a)
d = a.copy()
d.sort()
b = np.flip(d)[:5]
#print(b)
l = []
for n in b:
  l.append(np.where(a == n)[0][0])
print(l)


[27.62684215 14.64009987 21.80136195 42.39403048  1.23122395  6.95688692
 33.86670515 41.466785    7.69862289 29.17957314 44.67477576 11.25090398
 10.08108276  6.31046763 11.76517714 48.95256545 40.77247431  9.42510962
 40.99501269 14.42961361]
[48.95256545 44.67477576 42.39403048 41.466785   40.99501269]
[15, 10, 3, 7, 18]


In [149]:
nan_arr =np.array([1,2,3,np.nan,5,6,7,np.nan])
clean_arr = nan_arr[~np.isnan(nan_arr)]
#clean_arr = np.delete(nan_arr, np.where(np.isnan(nan_arr)))
print(clean_arr)



[1. 2. 3. 5. 6. 7.]
[1. 2. 3. 5. 6. 7.]


In [150]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
c = a-b
sq = c * c
print(np.sqrt(sq.sum()))


6.708203932499369


In [161]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
print(np.where(x == 1)[0][4])


8


In [167]:
np.random.seed(100)
arr = np.random.randint(0, 5, 10)
print(arr)
ms = arr < 0
for n in arr:
  ms[np.where(arr == n)[0][1:]]=True
print(ms)

[0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]
